In [ ]:
import tensorflow as tf

In [ ]:
hello=tf.constant('Hello world')

In [ ]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>

In [ ]:
hello_2=tf.constant('Hello world',shape=[6,2])

In [ ]:
tf.print(hello_2)

[["Hello world" "Hello world"]
 ["Hello world" "Hello world"]
 ["Hello world" "Hello world"]
 ["Hello world" "Hello world"]
 ["Hello world" "Hello world"]
 ["Hello world" "Hello world"]]


# MNIST database of handwritten digits
Dataset of 60000 28x28

In [ ]:
print(tf.__version__)

2.19.0


# Set Random Seed

In [ ]:
tf.random.set_seed(42)

In [ ]:
tf.keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [ ]:
data=tf.keras.datasets.mnist.load_data()
print(type(data))
print(len(data))

<class 'tuple'>
2


In [ ]:
data[1]

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [ ]:
train_data=data[0]   #This is (x_train,y_train)
test_data=data[1]    #This is (x_test,y_test)

print(type(train_data))
print(len(train_data))

<class 'tuple'>
2


In [ ]:
x_train=train_data[0]
y_train=train_data[1]

x_test=test_data[0]
y_test=test_data[1]

In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
(trainX,trainY),(testX,testY)=tf.keras.datasets.mnist.load_data()

## Print shape and some values of label

In [ ]:
trainX.shape

(60000, 28, 28)

In [ ]:
print(trainY.shape)
print("First 5 examples are:",trainY[0:5])

(60000,)
First 5 examples are: [5 0 4 1 9]


In [ ]:
testX.shape

(10000, 28, 28)

In [ ]:
testY.shape

(10000,)

In [ ]:
import matplotlib.pyplot as plt

#lets look at 21 pages
plt.figure(figsize=(13,13))

for i in range(21):
  plt.subplot(7,3,i+1)
  plt.imshow(trainX[i],cmap='gray')
  plt.title(f'label:{trainY[i]}')
  plt.axis('off')
plt.tight_layout()
plt.show()


# one-hot encoding

In [ ]:
trainY= tf.keras.utils.to_categorical(trainY,num_classes=10)
testY= tf.keras.utils.to_categorical(testY,num_classes=10)

Print shape amd some values

In [ ]:
print(trainY.shape)
print('First 5 examples now are:',trainY[0:5])

(60000, 10)
First 5 examples now are: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
print(testY.shape)
print('First 5 examples now are:', testY[0:5])

(10000, 10)
First 5 examples now are: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# Building a Model

In [ ]:
#Initialize sequential model
model=tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())


#Add Dense Layer which provides 10 outputs after applying softmax
model.add(tf.keras.layers.Dense(10,activation='softmax'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


# Complie the Model






In [ ]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(trainX, trainY, validation_data=(testX,testY), epochs=50, batch_size= trainX.shape[0])

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1945 - loss: 2.7938 - val_accuracy: 0.1774 - val_loss: 16.7522
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 813ms/step - accuracy: 0.2112 - loss: 2.7054 - val_accuracy: 0.1939 - val_loss: 11.5043
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 564ms/step - accuracy: 0.2265 - loss: 2.6206 - val_accuracy: 0.2109 - val_loss: 9.0490
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 715ms/step - accuracy: 0.2419 - loss: 2.5393 - val_accuracy: 0.2276 - val_loss: 7.5344
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 707ms/step - accuracy: 0.2579 - loss: 2.4616 - val_accuracy: 0.2460 - val_loss: 6.4777
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 651ms/step - accuracy: 0.2742 - loss: 2.3875 - val_accuracy: 0.2662 - val_loss: 5.6885
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 654ms/step - accuracy: 0.2912 - loss: 2.3168 - val_accuracy: 0.2879 - val_loss: 5.0738
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 802ms/step - accuracy: 0.3095 - loss: 2.2496 - val_accuracy: 0.3104 - val_loss: 

Predictions

In [ ]:
y_pred=model.predict(testX)
y_pred

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step


array([[6.5939617e-04, 1.8819144e-04, 2.5394181e-04, ..., 9.7327054e-01,
        5.3722966e-03, 9.5452770e-04],
       [5.1963512e-02, 1.9996457e-03, 2.4593718e-02, ..., 7.2699333e-07,
        2.9751689e-06, 1.9458997e-05],
       [6.4705908e-03, 8.9263463e-01, 1.1099359e-02, ..., 1.4699839e-02,
        1.1088033e-02, 1.7690556e-02],
       ...,
       [3.9121429e-03, 1.2713619e-02, 1.2115054e-03, ..., 1.2628394e-01,
        2.6210040e-01, 1.7122081e-01],
       [3.9514831e-07, 1.0322655e-03, 5.3494427e-05, ..., 5.0707406e-04,
        1.9040139e-02, 1.9753725e-06],
       [8.4821670e-04, 4.9619848e-07, 1.0232514e-04, ..., 6.1634237e-05,
        1.6800586e-05, 1.3016268e-07]], dtype=float32)

In [ ]:
tf.argmax(y_pred,axis=1)

<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7, 6, 1, ..., 8, 5, 6])>

In [ ]:
y_pred_classes=tf.argmax(y_pred,axis=1).numpy()

In [ ]:
y_pred_classes

array([7, 6, 1, ..., 8, 5, 6])

In [ ]:
tf.argmax(testY,axis=1)

<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7, 2, 1, ..., 4, 5, 6])>

In [ ]:
act_classes=tf.argmax(testY,axis=1).numpy()

In [ ]:
loss,accuracy=model.evaluate(testX,testY)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6660 - loss: 1.1255


In [ ]:
print("Test accuracy",accuracy)

Test accuracy 0.6963000297546387


Example of softmax

In [ ]:
logits=tf.constant([1.5,2,2.6,3])
p=tf.nn.softmax(logits)
p.numpy()

array([0.09867211, 0.1626828 , 0.29642737, 0.4422177 ], dtype=float32)