In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
tf.__version__

'2.19.0'

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
x=tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
y=tf.constant(10.6)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.600000381469727>

In [ ]:
s=tf.constant('India')
s

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [ ]:
l=tf.constant([1,2,3,4,5,6,7])
l

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
import numpy as np
l_2d=np.array([[1,2,3],[4,5,6]])
l=tf.constant(l_2d)
l

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t_3d=tf.constant([[[1,2,3],[4,5,6]]])
t_3d

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
# for customizing
t_2d=tf.constant([1,2,3,4],shape=(2,2),dtype='int32')
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_3d_1=tf.constant([[[1,2],[3,4],[5,6]]],dtype='float32')
t_3d_1


<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>

In [ ]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t_3d_1.shape

TensorShape([1, 3, 2])

# TensorFlow **Variable**

In [ ]:
import tensorflow as tf
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.name

'Variable:0'

In [ ]:
x.shape

TensorShape([4])

In [ ]:
y=tf.Variable([1.0,2.0,3.0])
y

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
z=tf.Variable(True,False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# Create TensorFlow Variable with different shape

In [ ]:
t_2d=tf.Variable([[1,2],[3,4]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Get the index of highest value

In [ ]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Change/Assign new value to tensor

In [ ]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.assign([4,5,6,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 8], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [ ]:
#Assign varialbe with another memory

In [ ]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 11,  8, 16], dtype=int32)>

Tensorflow Math modules

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a=10
b=20

In [ ]:
a+b

30

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# Addition of 2 values
l1=[1,2,3,4]
l2=[6,7,8,9]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [ ]:
# Addition of 2 tuples

In [ ]:
t1=(1,2,3,4)
t2=(6,7,7,9)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 10, 13], dtype=int32)>

In [ ]:
# Given a tensor x and y,power x^y

In [ ]:
x=tf.constant([[2,3],[3,3]])
y=tf.constant([[2,3],[3,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 27],
       [27, 81]], dtype=int32)>

In [ ]:
# tf.maths.abs
x=tf.constant([-2,3.4,3,25])
tf.abs(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2. ,  3.4,  3. , 25. ], dtype=float32)>